### ISSUE TITLE
Incompressible Navier-Stokes Finite-volume implementation

### ISSUE THREAD

**Issue by lindsayad** [idaholab/moose#15640]
## Reason
CFEM INS often struggles at corners where boundary condition discontinuities happen. Because finite volumes are face-based, they do not have this issue. Moreover, resolving oscillations for high Reynolds number flow is still an open research area (techniques like SUPG tend to damp oscillations, but they still do not ensure TVD).

## Design
The INSFV implementation will sit in the `navier_stokes` module alongside the CFEM INS implementation. We will use single standard variables to represent the velocity components instead of a single vector variable, since we don't have a vector test function to reduce the `computeQpResidual` computation to a single `ADReal`. A lot of the work will be done in materials with `ADMaterialProperty`. We will solve pressure and velocity in a single coupled system, which is in contrast to SIMPLE, PIMPLE, PISO algorithms widely used by the CFD community.

## Impact
Try to expand our CFD footprint. I imagine this as the starting point; eventually we'll want to add turbulence models, etc.

## To-Dos

- [x] Understand/fix two-element coupled behavior when using an `average advected_interp_method`. Refs https://github.com/idaholab/moose/issues/15640#issuecomment-697959979
- [x] Understand/fix `rc` interpolation artifacts at R=0 for RZ geometry. Refs RZ channel-flow input in #15644
- [x] Verify that `rc` interpolation works when finite volume fluid simulation is block restricted. Refs https://github.com/idaholab/moose/issues/15640#issuecomment-697959979

**Comment by lindsayad** [comment]
This will be a precursor to #9007

**Comment by pbalest** [comment]
Here is a list of thing I noticed:
---
1
---
I configured moose to use global indexing and when I try to scale the variables
```
[T_fluid]
    order = CONSTANT
    family = MONOMIAL
    initial_condition = 800.0
    scaling = 1e-2
    fv = true
[]
```
I get an error:
```
*** ERROR ***
/Users/balep/tests/pronghorn/testfv-mdaa04/transient_channel_with_energy.i:76: (Variables/T_fluid/scaling):
    Scaling with global AD indexing is not yet implemented.
```
2
---
Other AuxKernels(VectorMagnitudeAux) works with FV variables, but when I try to use `ParsedAux`:
```
[test_parsed]
    type = ParsedAux
    variable = test_parsed
    function = '-T_fluid'
    args = 'T_fluid'
[]
```
I get an error:

```
** ERROR ***
Variable 'args' is of a different C++ type than you tried to fetch it as.
```
3
---
When I use `average` for `advected_interp_method` I get a strange behaviour respect to when i use `upwind`.

# Average
![image](https://user-images.githubusercontent.com/35785210/94065816-d8b07f00-fda8-11ea-8e97-8c4a3124180c.png)
# Upwind
![image](https://user-images.githubusercontent.com/35785210/94065972-0eedfe80-fda9-11ea-9d4d-18f5c196cd3c.png)
Same results but `average` interpolation try to cancel the difference in value between two neighbor volumes.

4
---
When R=0 for RZ geometry `rc` interpolation has some issues

5
---
This is just a wishlist of things I have to still check but would be good having a test for it:

1. **Block restricted variables** and kernels, wondering if `rc` will detect that the volume is a boundary volume.
2. **FV FE Transfer**, some applications will stay FE (e.g. Griffin) so we have to make sure transfer between normal `CONSTANT MONOMIAL` and `FV CONSTANT MONOMIAL` works trough the multiapps.

**Comment by pbalest** [comment]
here is the file that I used for testing the capabilities:

[transient_channel_with_energy.txt](https://github.com/idaholab/moose/files/5271825/transient_channel_with_energy.txt)

**Comment by lindsayad** [comment]
> When I use `average` for `advected_interp_method` I get a strange behaviour respect to when i use `upwind`.

This is very interesting. Just getting around to this now. Ran your input and can reproduce the odd behavior. Thanks for the example @pbalest

**Comment by lindsayad** [comment]
Ok, it looks to me like there is not a bug in our implementation of the average interpolation, it's just that the average interpolation is bad for high Peclet numbers.

### Peclet = 1
![Pe-1e0](https://user-images.githubusercontent.com/10248304/99716163-a2b41200-2a5c-11eb-9d3d-a699e8dffb35.png)
### Peclet = 10
![Pe-1e1](https://user-images.githubusercontent.com/10248304/99716164-a34ca880-2a5c-11eb-8196-b3ecce05747e.png)
### Peclet = 100
![Pe-1e2](https://user-images.githubusercontent.com/10248304/99716166-a34ca880-2a5c-11eb-9a85-5f13e24325ea.png)
### Peclet = 1,000
![Pe-1e3](https://user-images.githubusercontent.com/10248304/99716168-a34ca880-2a5c-11eb-9d82-7ccf7685e78b.png)
### Peclet = 10,000
![Pe-1e4](https://user-images.githubusercontent.com/10248304/99716171-a3e53f00-2a5c-11eb-9f84-e7fddda37b22.png)
