### ISSUE TITLE
INSFV with porosity - PINSFV - Porous media navier stokes finite volume

### ISSUE THREAD

**Issue by lindsayad** [idaholab/moose#16756]
## Reason
Pretty much all of our deliverables for Pronghorn TH will require porosity

## Design
Hopefully inherit from existing INSFV kernels and apply porosity factor

## Impact
Enable modeling of porous problems with INSFV

## Tasks

- [x] Friction kernel
- [x] Solid/fluid heat exchange kernel (will be same for compressible)
- [x] Handle porosity jumps
- [x] Mu as function of temperature
