### ISSUE TITLE
Canonical porous INSFV, CNSFV tests

### ISSUE THREAD

**Issue by lindsayad** [idaholab/moose#16765]
## Reason
We want to be confident that our implementation is correct

## Design
Add `tests`

## Impact
Ensure that our users can be confident they have correct, verified models.

## To-Do List

- [ ] Straight channel uniform porosity/porosity jump, XY and RZ
- [ ] Elbow channel uniform porosity/double porosity jump, XY and RZ
- [ ] Divergent convergent loop with penalty BCs uniform porosity/porosity Jump, XY and RZ
- [ ] Closed loop forced convection, XY and RZ
- [ ] Closed loop natural convection, XY and RZ
- [ ] Open loop 2 parallel channels, XY and RZ

**Comment by lindsayad** [comment]
Duplicate of #21133
